### ISSUE TITLE
No longer working with IC5.5

### ISSUE THREAD

**Issue by xrissot-ibm** [benkroeger/passport-ibm-connections-oauth#2]
Hi,

This module is no longer working with IC5.5 due to OAUTH entry points change.

So for others persons that want to use it, open the strategy.js file and replace this line:
`const { authorizationPath = '/manage/oauth2/authorize' } = params;`
by:
`const { authorizationPath = '/oauth2/endpoint/connectionsProvider/authorize' } = params;`

And 
`const { tokenPath = '/manage/oauth2/token' } = params;`
by    
`const { tokenPath = '/oauth2/endpoint/connectionsProvider/token' } = params;  `

**Comment by benkroeger** [comment]
Hey Xavier, I'm afraid you overlooked that the code uses ES6 destructuring to retrieve `authorizationPath` as well as `tokenPath` from `params` object. The pathes that were valid for IBM Connections < 5.5 are set as default values and can easily be overwritten. The reason why I didn't set the IBM Connections 5.5 paths as default is that this would have broken every existing environment with an older version of IBM Connections.

Also, I've always registered a separate OAuth provider on IBM Connections site for my applications – so that I can set special configurations like `autoGrant=true` and `expires=never` for individual apps (clients) rather than all clients at once
